### ISSUE TITLE
[Question] Generate icon presentation in code

### ISSUE THREAD

**Issue by Lonli-Lokli** [kreuzerk/svg-to-ts#104]
Not sure if it possible with Typescript approach, but it will be very helpful to have visual presentation of all icons so developer will be just searching for the specific image which he needs.
Ie use case - find icon and determine it's name/code

**Comment by kreuzerk** [comment]
Hi @Lonli-Lokli thx for this question. 👍 

This is definitely possible. However it's not really the job of `svg-to-ts`. Usually, you should do this inside the project where you use `svg-to-ts`. Currently `svg-to-ts` supports multiple use cases. Therefore this might be a react library, an Angular library, a Vue library, or even a plain TS/JS library. 

In our case, we deliver the icons as a standalone library. I created a starter project that contains a preview of the icons. Feel free to check it out: https://github.com/kreuzerk/svg-icon-library-starter.

I am going to close this issue since it is not the job of `svg-to-ts` to create the preview pages.
