### ISSUE TITLE
Support Custom Name Delimiter 

### ISSUE THREAD

**Issue by reecemcd** [kreuzerk/svg-to-ts#11]
We utilize [@mdi](https://materialdesignicons.com/) icons and their docs list icon names with a `-` delimiter instead of `_`. Any way we could add an input flag to optionally render name values with a custom delimiter?

**Comment by kreuzerk** [comment]
Hi @reecemcd. Thanks for this issue. Yes it is possible. Just to be sure, you mean the delimiter in the generated names of the `type`?

**Comment by hrmcdonald** [comment]
Not sure exactly what you would refer to it as. Specifically, I mean the strings generated as values for the `name` properties in each icon constant. Because that is the value users pass to our icon component, it would be great if we could customize those to match our icon library's documentation formatting.

I'm just doing a replace for now, but an input option might be more ideal.

**Comment by hrmcdonald** [comment]
Not sure exactly what you would refer to it as. Specifically, I mean the strings generated as values for the `name` properties in each icon constant. Because that is the value users pass to our icon component, it would be great if we could customize those to match our icon library's documentation formatting.

I'm just doing a replace for now, but an input option might be more ideal.

**Comment by reecemcd** [comment]
Not sure exactly what you would refer to it as. Specifically, I mean the strings generated as values for the `name` properties in each icon constant. Because that is the value users pass to our icon component, it would be great if we could customize those to match our icon library's documentation formatting.

I'm just doing a replace for now, but an input option might be more ideal.

**Comment by kreuzerk** [comment]
Just published a new version (2.2.0) which allows you to pass in a delimiter flag. See the output from the help command:

`  -d --delimiter <Delimiter>     delimiter which is used to generate the types and name properties (CAMEL,KEBAB,SNAKE) (default: "SNAKE")
`

https://github.com/kreuzerk/svg-to-ts/pull/12

**Comment by kreuzerk** [comment]
Please let me know if something doesn't work for your use case.
