### ISSUE TITLE
Tree Shaking only works with sideEffects: false

### ISSUE THREAD

**Issue by dudewad** [kreuzerk/svg-to-ts#158]
I followed the tutorial you have on setting this up for Angular applications - first off, great work. Love the whole model of handling SVGs.

However, the whole benefit was tree-shakability, and on inspecting bundles I noticed that the way the exports work it seems to implicitly not be tree-shakable because there's a barrel file that re-exports everything - all svgs are imported in the final production bundle.

I dont know if its my setup (I'm having this as its own Angular lib to support the service and component, etc, which is imported into multiple applications). But in order to get tree shaking of the icons themselves to work, I had to use `sideEffects: false` in the root of my project's package.json.

Was this intentional, or is it a product of my particular project format? I'm also using nrwl nx so it could be relate to that. But `sideEffects: false` is a pretty heavy handed declaration that could cause pain later in other regards so I thought I would ask.

My configuration rc file looks like this:

```
{
  "srcFiles": [
    "./libs/core/assets/svgs/src/lib/assets/src/*.svg"
  ],
  "outputDirectory": "./libs/core/assets/svgs/src/lib/assets/dist",
  "interfaceName": "CoreSvg",
  "typeName": "coreSvg",
  "prefix": "coreSvg",
  "optimizeForLazyLoading": true,
  "modelFileName": "../../../models/core-svg.generated.model",
  "compileSources": true
}
```

Note I'm moving the model file to a models folder per my general "opinionated" lib structure, but that doesn't feel like it should matter much. The imports work as-is.

Curious if you have any thoughts. Everything is working for now, just was curious if this behavior is expcted.

Thanks

**Comment by kreuzerk** [comment]
Hi @dudewad. Thx a lot for the question. Your analysis is completely right. The `sideEffects` flag needs to be set to `false`. For the standard use case, this isn't a problem because you have a dedicated icon library which is published to npm. The only purpose of this lib is delivering icons.

However, in a Monorepo approach, things are different. I get that you probably don't want to set `sideEffects` to `false` at the root of your project. 

To be honest, I haven't yet thought much about using svg-to-ts in a monorepo. But now as I am thinking, I am not sure if svg-to-ts is even the right tool. Why do icons need to be part of the bundle? Couldn't you just deliver your SVG icons as assets? So you would create an assets library and then directly access those SVGs. In such a case they are not part of the bundle but would be loaded from the assets folder. 

This is just me thinking out loud. I haven't tried this yet. But I am curious about your thoughts.

**Comment by dudewad** [comment]
Sorry for the delay on this-- I didn't get a notification!

Honestly I've been doing so much app-level work that I haven't stopped to think about it too much. Currently in one of the various projects I'm involved in (a large enterprise library), we have an asset-specific lib within our monorepo that bundles ALL SVGs into one package.

This isn't great, because the file size has grown over time and doesn't get to shrink. It was the tree-shakability that your library brings that I was really interested in.

My monorepo is Nwrl NX (not sure if you're familiar) but the general structure there is a set of apps (1 or more) and then a set of libs where the vast majority of your code goes. I have a core UI and theming lib within that. However, now that I want to use svg-to-ts, I'm able to do SVGs as their own sub-library, and import them on a per-usage basis.

Re: using them as assets on a server -- I think this is fundamentally a no-go because I'm looking for 2 things:

1) To have the source injected directly on the page rather than in an element and loaded via  src attribute, this gives CSS access to styling and changing colors.
2) To have the icons load immediately as the bundle is loaded rather than as requests after a bundle is loaded or components become visible. The instantaneously-visible aspect of it is what I like.

The nice thing about the new format I'm using is that individual libraries can import and reference SVGs individually, which means that apps that don't import certain libs require 0 maintenance around adding/removing svg references, etc.

Hopefully any of that made sense. I'm a bit tired. :)

**Comment by kreuzerk** [comment]
@dudewad Thx a lof for that response. It's funny because it now happens that I am also creating a NX monorepo for a client. Soon we will also use icons in the monorepo. So I hope that I will have some time next week to analyze and implement this. Once I have it running in our application I will let you know about our approach and our findings.

**Comment by dudewad** [comment]
🎉 What a lovely coincidence!

Hopefully you find a need for it. Would love to get any updates as you have them. Also, thanks again for your work on the lib - works great. I'll check back and see if you come up with any updates or new recommendations based on a monorepo approach. Particularly if you go the route of having libs that incorporate svgs...!

**Comment by kreuzerk** [comment]
Hi @dudewad I just created a sample project that illustrates how to use svg-to-ts in a monorepo. https://github.com/kreuzerk/icons-monorepo. The example is in Angular though. Which framework are you using? 

Just asking because I recently just released some new TSX features that might be very interesting in case you use React.

**Comment by kreuzerk** [comment]
I will also close this issue for the moment since its not really a bug or a feature request. But feel free to continue writing here. Am very happy to discuss the use of svg-to-ts in a monorepo.

**Comment by dudewad** [comment]
@kreuzerk I'm using ngrx w/ angular. Will check out your monorepo stuff. Thanks a lot!

**Comment by MaChristmann** [comment]
@kreuzerk 
In the company I am working we have a similar setup as @dudewad 
As I see in your sample project you are using svg-to-ts-constants to generate the icons. 
I analysed the bundle using webpack-bundle-analyzer. The way the svg-to-ts library generates the icon that all icons will be part of the main-bundle. 

Is there a way that icons are tree shakable also for modules, so that an icon will only be part of a module-bundle instead of the main-bundle?

**Comment by kreuzerk** [comment]
Hey @MaChristmann. Yes absolutelly. You have to use the files converter. With that each icon is a single JS file, therefore its not only treeshakable but only "splitable". Means, icons will only end up in the used lazy feature bundle and if they are used accross multiple lazy bundles they will end up in a common chunk.

**Comment by MaChristmann** [comment]
Hey @kreuzerk thanks for getting back to me so fast. 

We are already using the files converter `svg-to-ts-files` with the latest version of svg-to-ts 12.0.0

The .svg assets are part of a separate Nwrl NX library in the project ("libs/resources")

Our svg-to-ts configuration is the following: 
```
  "svg-to-ts": {
    "conversionType": "files",
    "modelFileName": "svg-icon.model",
    "fileName": "svgIcon",
    "srcFiles": [
      "./libs/resources/svg/icons/**/*.svg"
    ],
    "outputDirectory": "./libs/resources/svg/icons",
    "interfaceName": "SvgIcon",
    "typeName": "SvgIconType",
    "prefix": "svgIcon",
    "svgoConfig": {
      "plugins": [...]
    },
    "compileSources": false
  }
```

and importing the SVG-icons in our modules/components like: 

```
import {
  SvgIcon,
  svgIconLosgehtsGuide,
} from '@resources/svg/icons';
```

Still all the generated files are part of the main bundle. There is not a single svgIcon in a module, even if it is only used in a lazy loaded module.
<img width="441" alt="Screenshot 2024-03-22 at 13 15 26" src="https://github.com/kreuzerk/svg-to-ts/assets/1323060/24a85d91-2dfc-40ca-97b9-45caeb193416">
