### ISSUE TITLE
Possibility to extract only the "d" attribute of the path

### ISSUE THREAD

**Issue by maku** [kreuzerk/svg-to-ts#222]
I would like to have the possibility to extract only the  svg.path.d from a svg element. 

Is this possible?

the export const should look like:

```
export const hubMap: {
  name: 'map';
  data: string;
} = {
  name: 'map',
  data: `M12 21.325q-.35 0-.7-.125t-.625-.375Q9.05 19.325 7.8 ...`
};
```

TIA

**Comment by kreuzerk** [comment]
Hi @maku thx a lot for the feature request. I think this is an interesting idea. But it kinda defeats the purpose of svg-to-ts since svg-to-ts only focuses on converting whole svgs. Furthermore I am not sure how this would look like if you have multiple paths with data attributes. Based on those reasons I don't see how we implement this in this library.
