### ISSUE TITLE
[Feature request] Data properties on icon objects

### ISSUE THREAD

**Issue by marco-martins** [kreuzerk/svg-to-ts#47]
Would be really helpful if could set more properties on icon objects:

example:
```javascript
export const myIconX: IconSet = {
  name: 'myIconNameX',
  data: '<svg...>',
  foo: 'bar'
}
```

**Comment by kreuzerk** [comment]
Hi @marco-martins thanks for bringing this up.
What's the use case for this? 

Also, where would the data come from - I guess you would pass it to svg-to-ts. Would each icon need to get specific data or would the passed data be the same for all icons?

**Comment by kreuzerk** [comment]
@marco-martins any news on that?

**Comment by marco-martins** [comment]
Hi @kreuzerk It was a long time ago, but I think on the time, my need it was to send specific data to a specific icon. 
Basically, I had a folder with a big number of icons and I did a script to generates all, some of the icons I would like the prefix to be _las_ (solid icons), _lar_ (regular icons) and _lab_ (brand icons). The idea was to send that prefix as a parameter, but could be useful to other thinks also.

I find out another way to do it without sending the prefix, I created 3 different folders to do that.
https://github.com/marco-martins/angular-line-awesome/blob/master/extract-icons.js

**Comment by kreuzerk** [comment]
Hi @marco-martins thanks a lot for your answer. I now see your use case. 
In version 5.3 we introduced the possibility to add a `--config` flag to specify a path to a configuration file. With this flag you should be able to create multiple configurations (for example for solid, regular and brand icons).

Since this problem can be solved with the config flag I will close this issue for now. Let me know if you need further support.
